apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: webapp-demo
  name: webapp-demo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: webapp-demo
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: webapp-demo
    spec:
      containers:
      - image: praveenshell123/test:25
        name: webapp-demo
        resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  name: argocd-lb-service
  labels:
    app: argocd-lb-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 9000
  selector:
    app: webapp-demo

